Search.appendIndex(
    [
                {
            "fqsen": "\\AuthController",
            "name": "AuthController",
            "summary": "",
            "url": "classes/AuthController.html"
        },                {
            "fqsen": "\\AuthController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020Template\u0020object\nInitialize\u0020Framework\u0020object",
            "url": "classes/AuthController.html#method___construct"
        },                {
            "fqsen": "\\AuthController\u003A\u003AshowLogin\u0028\u0029",
            "name": "showLogin",
            "summary": "set\u0020initial\u0020messages.",
            "url": "classes/AuthController.html#method_showLogin"
        },                {
            "fqsen": "\\AuthController\u003A\u003AshowForgotPass\u0028\u0029",
            "name": "showForgotPass",
            "summary": "",
            "url": "classes/AuthController.html#method_showForgotPass"
        },                {
            "fqsen": "\\AuthController\u003A\u003AforgotPass\u0028\u0029",
            "name": "forgotPass",
            "summary": "",
            "url": "classes/AuthController.html#method_forgotPass"
        },                {
            "fqsen": "\\AuthController\u003A\u003AdoSignup\u0028\u0029",
            "name": "doSignup",
            "summary": "Registers\u0020new\u0020racer\u0020in\u0020database",
            "url": "classes/AuthController.html#method_doSignup"
        },                {
            "fqsen": "\\AuthController\u003A\u003AcheckEmail\u0028\u0029",
            "name": "checkEmail",
            "summary": "Checks\u0020if\u0020the\u0020e\u002Dmail\u0020exists\u0020in\u0020the\u0020database.",
            "url": "classes/AuthController.html#method_checkEmail"
        },                {
            "fqsen": "\\AuthController\u003A\u003AactivateAccount\u0028\u0029",
            "name": "activateAccount",
            "summary": "",
            "url": "classes/AuthController.html#method_activateAccount"
        },                {
            "fqsen": "\\AuthController\u003A\u003AshowSignup\u0028\u0029",
            "name": "showSignup",
            "summary": "",
            "url": "classes/AuthController.html#method_showSignup"
        },                {
            "fqsen": "\\AuthController\u003A\u003A\u0024authmodel",
            "name": "authmodel",
            "summary": "",
            "url": "classes/AuthController.html#property_authmodel"
        },                {
            "fqsen": "\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/Controller.html"
        },                {
            "fqsen": "\\Controller\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020Template\u0020object\nInitialize\u0020Framework\u0020object",
            "url": "classes/Controller.html#method___construct"
        },                {
            "fqsen": "\\Controller\u003A\u003AdoLogin\u0028\u0029",
            "name": "doLogin",
            "summary": "starts\u0020the\u0020login\u0020process\nsets\u0020session\u0020id,\u0020user\u0020and\u0020session\u0020type",
            "url": "classes/Controller.html#method_doLogin"
        },                {
            "fqsen": "\\Controller\u003A\u003AdoUpload\u0028\u0029",
            "name": "doUpload",
            "summary": "",
            "url": "classes/Controller.html#method_doUpload"
        },                {
            "fqsen": "\\Controller\u003A\u003A\u0024f3",
            "name": "f3",
            "summary": "",
            "url": "classes/Controller.html#property_f3"
        },                {
            "fqsen": "\\Controller\u003A\u003A\u0024template",
            "name": "template",
            "summary": "",
            "url": "classes/Controller.html#property_template"
        },                {
            "fqsen": "\\Controller\u003A\u003A\u0024authmodel",
            "name": "authmodel",
            "summary": "",
            "url": "classes/Controller.html#property_authmodel"
        },                {
            "fqsen": "\\Controller\u003A\u003A\u0024validsession",
            "name": "validsession",
            "summary": "",
            "url": "classes/Controller.html#property_validsession"
        },                {
            "fqsen": "\\LicenceController",
            "name": "LicenceController",
            "summary": "",
            "url": "classes/LicenceController.html"
        },                {
            "fqsen": "\\LicenceController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020Template\u0020object\nInitialize\u0020Framework\u0020object",
            "url": "classes/LicenceController.html#method___construct"
        },                {
            "fqsen": "\\LicenceController\u003A\u003AlistCurrentLicence\u0028\u0029",
            "name": "listCurrentLicence",
            "summary": "",
            "url": "classes/LicenceController.html#method_listCurrentLicence"
        },                {
            "fqsen": "\\LicenceController\u003A\u003AlistAvailableLicences\u0028\u0029",
            "name": "listAvailableLicences",
            "summary": "",
            "url": "classes/LicenceController.html#method_listAvailableLicences"
        },                {
            "fqsen": "\\LicenceController\u003A\u003AbuyLicence\u0028\u0029",
            "name": "buyLicence",
            "summary": "",
            "url": "classes/LicenceController.html#method_buyLicence"
        },                {
            "fqsen": "\\LicenceController\u003A\u003A\u0024licencemodel",
            "name": "licencemodel",
            "summary": "",
            "url": "classes/LicenceController.html#property_licencemodel"
        },                {
            "fqsen": "\\ProfileController",
            "name": "ProfileController",
            "summary": "",
            "url": "classes/ProfileController.html"
        },                {
            "fqsen": "\\ProfileController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020Template\u0020object\nInitialize\u0020Framework\u0020object",
            "url": "classes/ProfileController.html#method___construct"
        },                {
            "fqsen": "\\ProfileController\u003A\u003A\u0024profilemodel",
            "name": "profilemodel",
            "summary": "",
            "url": "classes/ProfileController.html#property_profilemodel"
        },                {
            "fqsen": "\\ProfileController\u003A\u003A\u0024profiledata",
            "name": "profiledata",
            "summary": "",
            "url": "classes/ProfileController.html#property_profiledata"
        },                {
            "fqsen": "\\SponsorController",
            "name": "SponsorController",
            "summary": "",
            "url": "classes/SponsorController.html"
        },                {
            "fqsen": "\\SponsorController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020Template\u0020object\nInitialize\u0020Framework\u0020object",
            "url": "classes/SponsorController.html#method___construct"
        },                {
            "fqsen": "\\SponsorController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/SponsorController.html#method_index"
        },                {
            "fqsen": "\\SponsorController\u003A\u003AlistAll\u0028\u0029",
            "name": "listAll",
            "summary": "",
            "url": "classes/SponsorController.html#method_listAll"
        },                {
            "fqsen": "\\SponsorController\u003A\u003AlistOne\u0028\u0029",
            "name": "listOne",
            "summary": "",
            "url": "classes/SponsorController.html#method_listOne"
        },                {
            "fqsen": "\\SponsorController\u003A\u003AlistCurrentSponsor\u0028\u0029",
            "name": "listCurrentSponsor",
            "summary": "",
            "url": "classes/SponsorController.html#method_listCurrentSponsor"
        },                {
            "fqsen": "\\SponsorController\u003A\u003AlistRandomSponsor\u0028\u0029",
            "name": "listRandomSponsor",
            "summary": "",
            "url": "classes/SponsorController.html#method_listRandomSponsor"
        },                {
            "fqsen": "\\SponsorController\u003A\u003Acontract\u0028\u0029",
            "name": "contract",
            "summary": "",
            "url": "classes/SponsorController.html#method_contract"
        },                {
            "fqsen": "\\SponsorController\u003A\u003A\u0024sponsormodel",
            "name": "sponsormodel",
            "summary": "",
            "url": "classes/SponsorController.html#property_sponsormodel"
        },                {
            "fqsen": "\\Views",
            "name": "Views",
            "summary": "",
            "url": "classes/Views.html"
        },                {
            "fqsen": "\\Views\u003A\u003Abeforeroute\u0028\u0029",
            "name": "beforeroute",
            "summary": "",
            "url": "classes/Views.html#method_beforeroute"
        },                {
            "fqsen": "\\Views\u003A\u003Aafterroute\u0028\u0029",
            "name": "afterroute",
            "summary": "",
            "url": "classes/Views.html#method_afterroute"
        },                {
            "fqsen": "\\Views\u003A\u003AcheckSession\u0028\u0029",
            "name": "checkSession",
            "summary": "Return\u0020true\u0020if\u0020session\u0020is\u0020set\nSets\u0020global\u0020F3\u0020framework\u0020variables\nvariable\u0020sessionid\nvariable\u0020username\nvariable\u0020email\nvariable\u0020timeanddate",
            "url": "classes/Views.html#method_checkSession"
        },                {
            "fqsen": "\\Views\u003A\u003Adashboard\u0028\u0029",
            "name": "dashboard",
            "summary": "",
            "url": "classes/Views.html#method_dashboard"
        },                {
            "fqsen": "\\Views\u003A\u003Amailbox\u0028\u0029",
            "name": "mailbox",
            "summary": "",
            "url": "classes/Views.html#method_mailbox"
        },                {
            "fqsen": "\\Views\u003A\u003Alicences\u0028\u0029",
            "name": "licences",
            "summary": "",
            "url": "classes/Views.html#method_licences"
        },                {
            "fqsen": "\\Views\u003A\u003Ateams\u0028\u0029",
            "name": "teams",
            "summary": "",
            "url": "classes/Views.html#method_teams"
        },                {
            "fqsen": "\\Views\u003A\u003Asponsors\u0028\u0029",
            "name": "sponsors",
            "summary": "",
            "url": "classes/Views.html#method_sponsors"
        },                {
            "fqsen": "\\Views\u003A\u003Afinances\u0028\u0029",
            "name": "finances",
            "summary": "",
            "url": "classes/Views.html#method_finances"
        },                {
            "fqsen": "\\Views\u003A\u003Achampionships\u0028\u0029",
            "name": "championships",
            "summary": "",
            "url": "classes/Views.html#method_championships"
        },                {
            "fqsen": "\\Views\u003A\u003Aprofile\u0028\u0029",
            "name": "profile",
            "summary": "",
            "url": "classes/Views.html#method_profile"
        },                {
            "fqsen": "\\Views\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "",
            "url": "classes/Views.html#method_logout"
        },                {
            "fqsen": "\\Views\u003A\u003A\u0024page",
            "name": "page",
            "summary": "",
            "url": "classes/Views.html#property_page"
        },                {
            "fqsen": "\\Views\u003A\u003A\u0024sponsorcontroller",
            "name": "sponsorcontroller",
            "summary": "",
            "url": "classes/Views.html#property_sponsorcontroller"
        },                {
            "fqsen": "\\Views\u003A\u003A\u0024profilecontroller",
            "name": "profilecontroller",
            "summary": "",
            "url": "classes/Views.html#property_profilecontroller"
        },                {
            "fqsen": "\\Views\u003A\u003A\u0024licencecontroller",
            "name": "licencecontroller",
            "summary": "",
            "url": "classes/Views.html#property_licencecontroller"
        },                {
            "fqsen": "\\AuthModel",
            "name": "AuthModel",
            "summary": "",
            "url": "classes/AuthModel.html"
        },                {
            "fqsen": "\\AuthModel\u003A\u003AgenerateActivationKey\u0028\u0029",
            "name": "generateActivationKey",
            "summary": "Generates\u0020the\u0020unique\u0020id\u0020for\u0020the\u0020activation\u0020key",
            "url": "classes/AuthModel.html#method_generateActivationKey"
        },                {
            "fqsen": "\\AuthModel\u003A\u003AsendActivationKey\u0028\u0029",
            "name": "sendActivationKey",
            "summary": "",
            "url": "classes/AuthModel.html#method_sendActivationKey"
        },                {
            "fqsen": "\\AuthModel\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Checks\u0020user\u0020e\u002Dmail\nChecks\u0020user\u0020password\nChecks\u0020if\u0020user\u0020is\u0020active\nReturns\u0020loginvalid\nSets\u0020Messages\u0020to\u0020display\u0020if\u0020login\u0020is\u0020not\u0020ok",
            "url": "classes/AuthModel.html#method_login"
        },                {
            "fqsen": "\\AuthModel\u003A\u003Aactivate\u0028\u0029",
            "name": "activate",
            "summary": "Activates\u0020the\u0020user\u0020account\u0020by\u0020setting\nthe\u0020active\u0020in\u0020the\u0020db\u0020to\u0020true",
            "url": "classes/AuthModel.html#method_activate"
        },                {
            "fqsen": "\\AuthModel\u003A\u003ArandomString\u0028\u0029",
            "name": "randomString",
            "summary": "generates\u0020a\u0020random\u0020string\u0020to\u0020be\u0020used\u0020as\u0020recovery\u0020password",
            "url": "classes/AuthModel.html#method_randomString"
        },                {
            "fqsen": "\\AuthModel\u003A\u003AsendNewPassword\u0028\u0029",
            "name": "sendNewPassword",
            "summary": "",
            "url": "classes/AuthModel.html#method_sendNewPassword"
        },                {
            "fqsen": "\\AuthModel\u003A\u003A\u0024activationkey",
            "name": "activationkey",
            "summary": "",
            "url": "classes/AuthModel.html#property_activationkey"
        },                {
            "fqsen": "\\AuthModel\u003A\u003A\u0024hashedpassword",
            "name": "hashedpassword",
            "summary": "",
            "url": "classes/AuthModel.html#property_hashedpassword"
        },                {
            "fqsen": "\\AuthModel\u003A\u003A\u0024validlogin",
            "name": "validlogin",
            "summary": "",
            "url": "classes/AuthModel.html#property_validlogin"
        },                {
            "fqsen": "\\AuthModel\u003A\u003A\u0024active",
            "name": "active",
            "summary": "",
            "url": "classes/AuthModel.html#property_active"
        },                {
            "fqsen": "\\AuthModel\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/AuthModel.html#property_username"
        },                {
            "fqsen": "\\AuthModel\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/AuthModel.html#property_email"
        },                {
            "fqsen": "\\AuthModel\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/AuthModel.html#property_password"
        },                {
            "fqsen": "\\FileUpload",
            "name": "FileUpload",
            "summary": "",
            "url": "classes/FileUpload.html"
        },                {
            "fqsen": "\\FileUpload\u003A\u003AinitUpload\u0028\u0029",
            "name": "initUpload",
            "summary": "Initializes\u0020all\u0020functions\u0020to\u0020upload\u0020a\u0020file",
            "url": "classes/FileUpload.html#method_initUpload"
        },                {
            "fqsen": "\\FileUpload\u003A\u003AcheckFileType\u0028\u0029",
            "name": "checkFileType",
            "summary": "Checks\u0020if\u0020file\u0020type\u0020is\u0020image.",
            "url": "classes/FileUpload.html#method_checkFileType"
        },                {
            "fqsen": "\\FileUpload\u003A\u003AcheckFileSize\u0028\u0029",
            "name": "checkFileSize",
            "summary": "Checks\u0020if\u0020the\u0020file\u0020size\u0020is\u0020more\u0020than\u00204MB",
            "url": "classes/FileUpload.html#method_checkFileSize"
        },                {
            "fqsen": "\\FileUpload\u003A\u003AuniqueFileName\u0028\u0029",
            "name": "uniqueFileName",
            "summary": "Generates\u0020a\u0020unique\u0020name\u0020for\u0020the\u0020uploaded\u0020file",
            "url": "classes/FileUpload.html#method_uniqueFileName"
        },                {
            "fqsen": "\\FileUpload\u003A\u003AuploadFile\u0028\u0029",
            "name": "uploadFile",
            "summary": "",
            "url": "classes/FileUpload.html#method_uploadFile"
        },                {
            "fqsen": "\\FileUpload\u003A\u003A\u0024currentfile",
            "name": "currentfile",
            "summary": "",
            "url": "classes/FileUpload.html#property_currentfile"
        },                {
            "fqsen": "\\FileUpload\u003A\u003A\u0024serverroot",
            "name": "serverroot",
            "summary": "",
            "url": "classes/FileUpload.html#property_serverroot"
        },                {
            "fqsen": "\\FileUpload\u003A\u003A\u0024destinationfolder",
            "name": "destinationfolder",
            "summary": "",
            "url": "classes/FileUpload.html#property_destinationfolder"
        },                {
            "fqsen": "\\FileUpload\u003A\u003A\u0024filename",
            "name": "filename",
            "summary": "",
            "url": "classes/FileUpload.html#property_filename"
        },                {
            "fqsen": "\\FileUpload\u003A\u003A\u0024filetype",
            "name": "filetype",
            "summary": "",
            "url": "classes/FileUpload.html#property_filetype"
        },                {
            "fqsen": "\\FileUpload\u003A\u003A\u0024fileextension",
            "name": "fileextension",
            "summary": "",
            "url": "classes/FileUpload.html#property_fileextension"
        },                {
            "fqsen": "\\FileUpload\u003A\u003A\u0024filesize",
            "name": "filesize",
            "summary": "",
            "url": "classes/FileUpload.html#property_filesize"
        },                {
            "fqsen": "\\FileUpload\u003A\u003A\u0024imgwidth",
            "name": "imgwidth",
            "summary": "size\u0020in\u0020bytes",
            "url": "classes/FileUpload.html#property_imgwidth"
        },                {
            "fqsen": "\\FileUpload\u003A\u003A\u0024imgheigth",
            "name": "imgheigth",
            "summary": "",
            "url": "classes/FileUpload.html#property_imgheigth"
        },                {
            "fqsen": "\\FileUpload\u003A\u003A\u0024newfilename",
            "name": "newfilename",
            "summary": "",
            "url": "classes/FileUpload.html#property_newfilename"
        },                {
            "fqsen": "\\FileUpload\u003A\u003A\u0024path",
            "name": "path",
            "summary": "",
            "url": "classes/FileUpload.html#property_path"
        },                {
            "fqsen": "\\FileUpload\u003A\u003A\u0024filesizeok",
            "name": "filesizeok",
            "summary": "complete\u0020path\u0020for\u0020the\u0020file\u0020upload\u0020including\u0020the\u0020filename",
            "url": "classes/FileUpload.html#property_filesizeok"
        },                {
            "fqsen": "\\FileUpload\u003A\u003A\u0024filetypeok",
            "name": "filetypeok",
            "summary": "",
            "url": "classes/FileUpload.html#property_filetypeok"
        },                {
            "fqsen": "\\LicenceModel",
            "name": "LicenceModel",
            "summary": "",
            "url": "classes/LicenceModel.html"
        },                {
            "fqsen": "\\LicenceModel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "set\u0020the\u0020framework\u0020instance\u0020\u0024f3\nset\u0020the\u0020template\u0020instance\u0020\u0024template",
            "url": "classes/LicenceModel.html#method___construct"
        },                {
            "fqsen": "\\LicenceModel\u003A\u003AgetCurrent\u0028\u0029",
            "name": "getCurrent",
            "summary": "",
            "url": "classes/LicenceModel.html#method_getCurrent"
        },                {
            "fqsen": "\\LicenceModel\u003A\u003AgetAvailableLicences\u0028\u0029",
            "name": "getAvailableLicences",
            "summary": "",
            "url": "classes/LicenceModel.html#method_getAvailableLicences"
        },                {
            "fqsen": "\\LicenceModel\u003A\u003A\u0024licencedata",
            "name": "licencedata",
            "summary": "",
            "url": "classes/LicenceModel.html#property_licencedata"
        },                {
            "fqsen": "\\LicenceModel\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/LicenceModel.html#property_email"
        },                {
            "fqsen": "\\LicenceModel\u003A\u003A\u0024licences",
            "name": "licences",
            "summary": "",
            "url": "classes/LicenceModel.html#property_licences"
        },                {
            "fqsen": "\\Model",
            "name": "Model",
            "summary": "",
            "url": "classes/Model.html"
        },                {
            "fqsen": "\\Model\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "set\u0020the\u0020framework\u0020instance\u0020\u0024f3\nset\u0020the\u0020template\u0020instance\u0020\u0024template",
            "url": "classes/Model.html#method___construct"
        },                {
            "fqsen": "\\Model\u003A\u003AmapDbTable\u0028\u0029",
            "name": "mapDbTable",
            "summary": "Maps\u0020database\u0020table\u0020to\u0020object\u0020\u0024dbdata\n\u0024dbtable\u0020is\u0020the\u0020name\u0020of\u0020database\u0020table\u0020to\u0020be\u0020mapped",
            "url": "classes/Model.html#method_mapDbTable"
        },                {
            "fqsen": "\\Model\u003A\u003AconnectMySQL\u0028\u0029",
            "name": "connectMySQL",
            "summary": "Connects\u0020to\u0020MySQL\u0020database\nSYSDB,\u0020DBUSERNAME,\u0020DBPASSWORD\u0020are\u0020in\u0020the\u0020config.ini",
            "url": "classes/Model.html#method_connectMySQL"
        },                {
            "fqsen": "\\Model\u003A\u003AgetByEmail\u0028\u0029",
            "name": "getByEmail",
            "summary": "gets\u0020data\u0020from\u0020database",
            "url": "classes/Model.html#method_getByEmail"
        },                {
            "fqsen": "\\Model\u003A\u003AencryptPassword\u0028\u0029",
            "name": "encryptPassword",
            "summary": "Encrypts\u0020a\u0020given\u0020password",
            "url": "classes/Model.html#method_encryptPassword"
        },                {
            "fqsen": "\\Model\u003A\u003AsetNewPassword\u0028\u0029",
            "name": "setNewPassword",
            "summary": "Save\u0020the\u0020new\u0020encrypted\u0020password\u0020in\u0020to\u0020database",
            "url": "classes/Model.html#method_setNewPassword"
        },                {
            "fqsen": "\\Model\u003A\u003A\u0024f3",
            "name": "f3",
            "summary": "",
            "url": "classes/Model.html#property_f3"
        },                {
            "fqsen": "\\Model\u003A\u003A\u0024appdatabase",
            "name": "appdatabase",
            "summary": "",
            "url": "classes/Model.html#property_appdatabase"
        },                {
            "fqsen": "\\Model\u003A\u003A\u0024template",
            "name": "template",
            "summary": "",
            "url": "classes/Model.html#property_template"
        },                {
            "fqsen": "\\Model\u003A\u003A\u0024dbdata",
            "name": "dbdata",
            "summary": "",
            "url": "classes/Model.html#property_dbdata"
        },                {
            "fqsen": "\\ProfileModel",
            "name": "ProfileModel",
            "summary": "",
            "url": "classes/ProfileModel.html"
        },                {
            "fqsen": "\\ProfileModel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "set\u0020the\u0020framework\u0020instance\u0020\u0024f3\nset\u0020the\u0020template\u0020instance\u0020\u0024template",
            "url": "classes/ProfileModel.html#method___construct"
        },                {
            "fqsen": "\\ProfileModel\u003A\u003AgetCurrentProfile\u0028\u0029",
            "name": "getCurrentProfile",
            "summary": "Get\u0020the\u0020data\u0020for\u0020the\u0020current\u0020profile\u0020by\u0020the\u0020e\u002Dmail\nemail\u0020is\u0020set\u0020in\u0020f3\u0020global\u0020variable\u0020email\u0020in\u0020the\u0020views.php\u0020in\u0020checkSession",
            "url": "classes/ProfileModel.html#method_getCurrentProfile"
        },                {
            "fqsen": "\\ProfileModel\u003A\u003AgetOne\u0028\u0029",
            "name": "getOne",
            "summary": "",
            "url": "classes/ProfileModel.html#method_getOne"
        },                {
            "fqsen": "\\ProfileModel\u003A\u003AgetXRandomly\u0028\u0029",
            "name": "getXRandomly",
            "summary": "",
            "url": "classes/ProfileModel.html#method_getXRandomly"
        },                {
            "fqsen": "\\ProfileModel\u003A\u003AgetCurrent\u0028\u0029",
            "name": "getCurrent",
            "summary": "",
            "url": "classes/ProfileModel.html#method_getCurrent"
        },                {
            "fqsen": "\\ProfileModel\u003A\u003A\u0024profiledata",
            "name": "profiledata",
            "summary": "",
            "url": "classes/ProfileModel.html#property_profiledata"
        },                {
            "fqsen": "\\ProfileModel\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/ProfileModel.html#property_email"
        },                {
            "fqsen": "\\SignupModel",
            "name": "SignupModel",
            "summary": "",
            "url": "classes/SignupModel.html"
        },                {
            "fqsen": "\\SignupModel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "set\u0020the\u0020framework\u0020instance\u0020\u0024f3\nset\u0020the\u0020template\u0020instance\u0020\u0024template",
            "url": "classes/SignupModel.html#method___construct"
        },                {
            "fqsen": "\\SignupModel\u003A\u003AinitSignup\u0028\u0029",
            "name": "initSignup",
            "summary": "",
            "url": "classes/SignupModel.html#method_initSignup"
        },                {
            "fqsen": "\\SignupModel\u003A\u003AinitData\u0028\u0029",
            "name": "initData",
            "summary": "initializes\u0020data\u0020from\u0020data\u0020received\u0020from\u0020registration\u0020form\nencrypt\u0020the\u0020password\ngenerates\u0020an\u0020activation\u0020token",
            "url": "classes/SignupModel.html#method_initData"
        },                {
            "fqsen": "\\SignupModel\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Saves\u0020the\u0020data",
            "url": "classes/SignupModel.html#method_register"
        },                {
            "fqsen": "\\SignupModel\u003A\u003A\u0024authmodel",
            "name": "authmodel",
            "summary": "",
            "url": "classes/SignupModel.html#property_authmodel"
        },                {
            "fqsen": "\\SponsorContract",
            "name": "SponsorContract",
            "summary": "",
            "url": "classes/SponsorContract.html"
        },                {
            "fqsen": "\\SponsorContract\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "set\u0020the\u0020framework\u0020instance\u0020\u0024f3\nset\u0020the\u0020template\u0020instance\u0020\u0024template",
            "url": "classes/SponsorContract.html#method___construct"
        },                {
            "fqsen": "\\SponsorContract\u003A\u003AcreateContract\u0028\u0029",
            "name": "createContract",
            "summary": "",
            "url": "classes/SponsorContract.html#method_createContract"
        },                {
            "fqsen": "\\SponsorContract\u003A\u003AdeleteContract\u0028\u0029",
            "name": "deleteContract",
            "summary": "",
            "url": "classes/SponsorContract.html#method_deleteContract"
        },                {
            "fqsen": "\\SponsorContract\u003A\u003AgenerateContractValue\u0028\u0029",
            "name": "generateContractValue",
            "summary": "Generates\u0020a\u0020value\u0020for\u0020the\u0020contract",
            "url": "classes/SponsorContract.html#method_generateContractValue"
        },                {
            "fqsen": "\\SponsorContract\u003A\u003AgenerateContractDays\u0028\u0029",
            "name": "generateContractDays",
            "summary": "Generates\u0020a\u0020number\u0020of\u0020months\u0020for\u0020the\u0020contract\u0020duration",
            "url": "classes/SponsorContract.html#method_generateContractDays"
        },                {
            "fqsen": "\\SponsorContract\u003A\u003A\u0024minvalue",
            "name": "minvalue",
            "summary": "",
            "url": "classes/SponsorContract.html#property_minvalue"
        },                {
            "fqsen": "\\SponsorContract\u003A\u003A\u0024maxvalue",
            "name": "maxvalue",
            "summary": "",
            "url": "classes/SponsorContract.html#property_maxvalue"
        },                {
            "fqsen": "\\SponsorContract\u003A\u003A\u0024minmonths",
            "name": "minmonths",
            "summary": "",
            "url": "classes/SponsorContract.html#property_minmonths"
        },                {
            "fqsen": "\\SponsorContract\u003A\u003A\u0024maxmonths",
            "name": "maxmonths",
            "summary": "",
            "url": "classes/SponsorContract.html#property_maxmonths"
        },                {
            "fqsen": "\\SponsorContract\u003A\u003A\u0024racer",
            "name": "racer",
            "summary": "",
            "url": "classes/SponsorContract.html#property_racer"
        },                {
            "fqsen": "\\SponsorContract\u003A\u003A\u0024team",
            "name": "team",
            "summary": "",
            "url": "classes/SponsorContract.html#property_team"
        },                {
            "fqsen": "\\SponsorContract\u003A\u003A\u0024startdate",
            "name": "startdate",
            "summary": "",
            "url": "classes/SponsorContract.html#property_startdate"
        },                {
            "fqsen": "\\SponsorContract\u003A\u003A\u0024enddate",
            "name": "enddate",
            "summary": "",
            "url": "classes/SponsorContract.html#property_enddate"
        },                {
            "fqsen": "\\SponsorContract\u003A\u003A\u0024contractvalue",
            "name": "contractvalue",
            "summary": "",
            "url": "classes/SponsorContract.html#property_contractvalue"
        },                {
            "fqsen": "\\SponsorContract\u003A\u003A\u0024sponsor",
            "name": "sponsor",
            "summary": "",
            "url": "classes/SponsorContract.html#property_sponsor"
        },                {
            "fqsen": "\\SponsorModel",
            "name": "SponsorModel",
            "summary": "",
            "url": "classes/SponsorModel.html"
        },                {
            "fqsen": "\\SponsorModel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "set\u0020the\u0020framework\u0020instance\u0020\u0024f3\nset\u0020the\u0020template\u0020instance\u0020\u0024template",
            "url": "classes/SponsorModel.html#method___construct"
        },                {
            "fqsen": "\\SponsorModel\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Loads\u0020all\u0020sponsor\u0020data\u0020in\u0020to\u0020sponsordata",
            "url": "classes/SponsorModel.html#method_getAll"
        },                {
            "fqsen": "\\SponsorModel\u003A\u003AgetOne\u0028\u0029",
            "name": "getOne",
            "summary": "",
            "url": "classes/SponsorModel.html#method_getOne"
        },                {
            "fqsen": "\\SponsorModel\u003A\u003AgetXRandomly\u0028\u0029",
            "name": "getXRandomly",
            "summary": "",
            "url": "classes/SponsorModel.html#method_getXRandomly"
        },                {
            "fqsen": "\\SponsorModel\u003A\u003AgetCurrent\u0028\u0029",
            "name": "getCurrent",
            "summary": "",
            "url": "classes/SponsorModel.html#method_getCurrent"
        },                {
            "fqsen": "\\SponsorModel\u003A\u003A\u0024sponsordata",
            "name": "sponsordata",
            "summary": "",
            "url": "classes/SponsorModel.html#property_sponsordata"
        },                {
            "fqsen": "\\SponsorModel\u003A\u003A\u0024minvalue",
            "name": "minvalue",
            "summary": "",
            "url": "classes/SponsorModel.html#property_minvalue"
        },                {
            "fqsen": "\\SponsorModel\u003A\u003A\u0024maxvalue",
            "name": "maxvalue",
            "summary": "",
            "url": "classes/SponsorModel.html#property_maxvalue"
        },                {
            "fqsen": "\\SponsorModel\u003A\u003A\u0024minmonths",
            "name": "minmonths",
            "summary": "",
            "url": "classes/SponsorModel.html#property_minmonths"
        },                {
            "fqsen": "\\SponsorModel\u003A\u003A\u0024maxmonths",
            "name": "maxmonths",
            "summary": "",
            "url": "classes/SponsorModel.html#property_maxmonths"
        },                {
            "fqsen": "\\SponsorModel\u003A\u003A\u0024startdate",
            "name": "startdate",
            "summary": "",
            "url": "classes/SponsorModel.html#property_startdate"
        },                {
            "fqsen": "\\SponsorModel\u003A\u003A\u0024enddate",
            "name": "enddate",
            "summary": "",
            "url": "classes/SponsorModel.html#property_enddate"
        },                {
            "fqsen": "\\SponsorModel\u003A\u003A\u0024contractvalue",
            "name": "contractvalue",
            "summary": "",
            "url": "classes/SponsorModel.html#property_contractvalue"
        },                {
            "fqsen": "\\SponsorModel\u003A\u003A\u0024sponsorlist",
            "name": "sponsorlist",
            "summary": "",
            "url": "classes/SponsorModel.html#property_sponsorlist"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
